from enum import Enum


class AuthState(str, Enum):
    IDENTIFIER_REQUIRED = "IDENTIFIER_REQUIRED"
    CREATE_ACCOUNT = "CREATE_ACCOUNT"
    VERIFY_EMAIL = "VERIFY_EMAIL"
    VERIFY_PHONE = "VERIFY_PHONE"
    ADD_EMAIL_OPTIONAL = "ADD_EMAIL_OPTIONAL"
    ADD_PHONE_OPTIONAL = "ADD_PHONE_OPTIONAL"
    AUTHENTICATED = "AUTHENTICATED"
