class Events:
    USER_CREATED = "USER_CREATED"
    USER_LOGGED_IN = "USER_LOGGED_IN"
    OTP_VERIFIED = "OTP_VERIFIED"
    USER_FULLY_VERIFIED = "USER_FULLY_VERIFIED"

    ORDER_CREATED = "ORDER_CREATED"
    ORDER_PAID = "ORDER_PAID"
    ORDER_PACKED = "ORDER_PACKED"
    ORDER_SHIPPED = "ORDER_SHIPPED"
    ORDER_DELIVERED = "ORDER_DELIVERED"

    ORDER_CANCELLED = "ORDER_CANCELLED"
    ORDER_RECEIPT_GENERATED = "ORDER_RECEIPT_GENERATED"
